---

- set_fact:
    strongswan_additional_plugins: []

- name: Fedora | Install strongSwan
  dnf:
    name: strongswan
    state: latest

- name: Fedora | Enable services
  service: name={{ item }} enabled=yes
  with_items:
    - strongswan

- name: Fedora | Ensure that the strongswan service directory exist
  file:
    path: /etc/systemd/system/strongswan.service.d/
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Fedora | Setup the cgroup limitations for the ipsec daemon
  template:
    src: 100-CustomLimitations.conf.j2
    dest: /etc/systemd/system/strongswan.service.d/100-CustomLimitations.conf
  notify:
    - daemon-reload
    - restart strongswan

- name: Fedora | disable and stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Fedora | start and enable iptables
  service:
    name: iptables
    state: started
    enabled: yes
  service:
    name: ip6tables
    state: started
    enabled: yes

- include_tasks: iptables_fedora.yml
  tags: iptables
