---

- name: Iptables configured
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - { src: rules.v4.j2, dest: /etc/sysconfig/iptables }
  notify:
    - restart iptables-fedora-v4

- name: Iptables configured
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0640
  when: ipv6_support
  with_items:
    - { src: rules.v6.j2, dest: /etc/sysconfig/ip6tables }
  notify:
    - restart iptables-fedora-v6
