- name: restart strongswan
  service: name=strongswan state=restarted

- name: daemon-reload
  shell: systemctl daemon-reload

- name: restart apparmor
  service: name=apparmor state=restarted

- name: save iptables
  shell: service netfilter-persistent save

- name: restart iptables
  service: name=netfilter-persistent state=restarted

- name: rereadcrls
  shell: ipsec rereadcrls; ipsec purgecrls

- name: save iptables-fedora-v4
  shell: iptables save

- name: save iptables-fedora-v6
  shell: ip6tables-save

- name: restart iptables-fedora-v4
  service: name=iptables state=restarted

- name: restart iptables-fedora-v6
  service: name=ip6tables state=restarted
