---
- name: WireGuard repository configured
  yum_repository:
    name: wireguard
    description: Copr Wireguard repo
    baseurl: https://copr-be.cloud.fedoraproject.org/results/jdoss/wireguard/fedora-$releasever-$basearch/
    gpgcheck: yes
    gpgcakey: https://copr-be.cloud.fedoraproject.org/results/jdoss/wireguard/pubkey.gpg
  notify: yum-clean-metadata

- name: WireGuard installed
  yum:
    name: "{{ item }}"
    with_items:
      - wireguard-dkms
      - wireguard-tools
    state: present

- name: WireGuard reload-module-on-update
  file:
    dest: /etc/wireguard/.reload-module-on-update
    state: touch

- set_fact:
    service_name: "wg-quick@{{ wireguard_interface }}"
  tags: always
