---
- name: WireGuard repository configured
  yum_repository:
    name: wireguard
    description: Copr Wireguard repo
    baseurl: https://copr-be.cloud.fedoraproject.org/results/jdoss/wireguard/fedora-$releasever-$basearch/
    gpgcheck: yes
    gpgcakey: https://copr-be.cloud.fedoraproject.org/results/jdoss/wireguard/pubkey.gpg
  notify: yum-clean-metadata

- name: WireGuard installed
  yum:
    name:
      - wireguard-dkms
      - wireguard-tools
    state: latest

- name: Create WireGuard directory
  file:
    path: /etc/wireguard
    state: directory
    mode: 0755

- name: WireGuard reload-module-on-update
  file:
    dest: /etc/wireguard/.reload-module-on-update
    state: touch

- set_fact:
    service_name: "wg-quick@{{ wireguard_interface }}"
  tags: always